// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_o_YPbz2KyPcHsI2vKdDCioGUlEeagg',
    appId: '1:703118125005:web:e7dfea0c920ddb53234684',
    messagingSenderId: '703118125005',
    projectId: 'amburush2',
    authDomain: 'amburush2.firebaseapp.com',
    storageBucket: 'amburush2.firebasestorage.app',
    measurementId: 'G-80DP990JEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTGIYAo94fvDINZiu3t46PwYjA8Hn31LE',
    appId: '1:703118125005:android:3b232b57a0ba4e0f234684',
    messagingSenderId: '703118125005',
    projectId: 'amburush2',
    storageBucket: 'amburush2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFTzkFrv9L_-r2FDLEPVOk4raSfifj7UU',
    appId: '1:703118125005:ios:206f9e3401b191eb234684',
    messagingSenderId: '703118125005',
    projectId: 'amburush2',
    storageBucket: 'amburush2.firebasestorage.app',
    iosBundleId: 'com.example.amburush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFTzkFrv9L_-r2FDLEPVOk4raSfifj7UU',
    appId: '1:703118125005:ios:206f9e3401b191eb234684',
    messagingSenderId: '703118125005',
    projectId: 'amburush2',
    storageBucket: 'amburush2.firebasestorage.app',
    iosBundleId: 'com.example.amburush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg_o_YPbz2KyPcHsI2vKdDCioGUlEeagg',
    appId: '1:703118125005:web:9ddb68f62084fd37234684',
    messagingSenderId: '703118125005',
    projectId: 'amburush2',
    authDomain: 'amburush2.firebaseapp.com',
    storageBucket: 'amburush2.firebasestorage.app',
    measurementId: 'G-BHR6L9N7H5',
  );
}
